on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        default: "0.0.0.0"
        required: true
        type: string
      create-release:
        type: boolean
        description: "Create Release"

jobs:
  release:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os: 
          - runs-on: ubuntu-latest
            arch: linux-x64

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Build
        run: |
          npm install vite
          npm run build

      - name: compress package
        run: 7z a output.zip ./dist/*

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: utaformatix-${{ matrix.os.arch }}.zip
          path: utaformatix-${{ matrix.os.arch }}.zip

      - name: Create release 
        if: ${{ inputs.create-release }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          files: |
            tagviewer.zip
